/**
 * Recommendations Slice
 * ----------------------
 * This Redux slice manages the "Recommendations" state within the application, allowing for initialization
 * with an array of `RecommendationModel` items.
 * 
 * Imports:
 * - `PayloadAction` and `createSlice` from Redux Toolkit: Used to define and manage the slice, and handle payload data.
 * - `RecommendationModel`: Data model representing a recommendation item, which could include fields like author, content, and date.
 */

import { PayloadAction, createSlice } from "@reduxjs/toolkit";
import RecommendationModel from "../Models/RecommendationModel";

/**
 * initAll Function
 * -----------------
 * Reducer function that initializes the recommendations state with a new array of `RecommendationModel` items.
 * 
 * Parameters:
 * - `currentState`: Current state of recommendations, an array of `RecommendationModel`.
 * - `action`: Redux action containing a payload with an array of `RecommendationModel` items to populate the new state.
 * 
 * Returns:
 * - The new state, an array of all recommendations from the action payload.
 */
function initAll(currentState: RecommendationModel[], action: PayloadAction<RecommendationModel[]>): RecommendationModel[] {
    const allRecommendations = action.payload; // Retrieves all recommendations from the action payload
    return allRecommendations;                 // Sets the state to the payload array
}

/**
 * recommendationsSlice
 * ----------------------
 * Creates a Redux slice for managing the "Recommendations" section in the application state.
 * 
 * Properties:
 * - `name`: Defines the slice name as "recommendations" for easy referencing.
 * - `initialState`: Sets an initial empty array, indicating no recommendations loaded by default.
 * - `reducers`: Specifies available reducer functions, here defining only `initAll` for initializing recommendations.
 */
const recommendationsSlice = createSlice({
    name: "recommendations",     // Identifier for the slice in the Redux store
    initialState: [],            // Initial empty state
    reducers: { initAll }        // Reducers defining actions on this slice, with `initAll` for state initialization
});

/**
 * recommendationsActionCreators
 * ------------------------------
 * Exports the action creators generated by Redux Toolkit for the recommendations slice, including `initAll`.
 */
export const recommendationsActionCreators = recommendationsSlice.actions;

/**
 * recommendationsReducersContainer
 * ---------------------------------
 * Exports the reducer for this slice, enabling it to be combined in the Redux store.
 */
export const recommendationsReducersContainer = recommendationsSlice.reducer;